### ISSUE TITLE
HTTP HEAD request should be used instead of GET for initial request

### ISSUE THREAD

**Issue by mhoglan** [rlmcpherson/s3gof3r#59]
To determine the amount of chunks the content-length of the object is needed.  A HTTP GET is performed and the body is not read from the response in order to get this header.  A HTTP HEAD would have returned this information and would have not included the payload.   This would also eliminate unnecessary TCP packets that are carrying segments of the payload but never read.

There is an opportunity I think to optimize further and have the initial request be a HTTP GET with the byte range for the first chunk.  HTTP spec says that if the byte range exceeds the content-length, then the content-length is used.  Then the initial response to get the content length for calculating chunk totals could re-used and there would not need to be a second HTTP GET request.   Could also determine that if there is no need for any additional chunks, then do not startup any workers and just proceed with current response processing.   This is bigger work and probably should be moved into its own feature / issue.  Or this issue can stay open to resolve.

**Comment by mhoglan** [comment]
I believe these extra HTTP GET requests can trigger AWS throttling if you are dealing with smaller files and you are using multiple instances of the library across nodes for distributed downloads (in my case, ingestion into a database).   Trimming requests from 2 to 1 per file is significant reduction in the HTTP request rate.  Believe the rate limit is around a few hundred a second.

**Comment by rlmcpherson** [comment]
The request was switched from HEAD to GET in 9829c14 to improve the error messaging from non-successful HTTP responses. HEAD requests don't include this. In practice, any difference in performance seems to be negligible since the response body is not read internally unless it is less than 2048 bytes. https://sourcegraph.com/github.com/golang/go@ac452349e4f40c30d50f9922bf2c4592e748ce5e/.tree/src/net/http/client.go#startline=387&endline=387

The optimization to read small files directly from the initial get request is something I've considered adding but haven't due to additional complexity, both internally and for the API. If it can be done without breaking changes or too much additional complexity, though, I'm certainly open to more discussion or a PR. 

As far as S3 rate-limiting, can you point to documentation that HEAD requests instead of GET requests impact throttling (I haven't seen any discussion of that before) or were you referring only to the single get request per download optimization?

**Comment by mhoglan** [comment]
I could not find a straight answer if HEAD counts the same as GET in regards to rate limiting.  I can see it both ways from their end, HEAD requests are just as expensive as GET for small files, or they may have it optimized to generate HEAD responses without as much work.

I was thinking that if we could find a way to reuse the 1st GET as part of the chunk downloads, that it would allow 1 GET for smaller ( < PartSize) files, where right now that is 2 GETs.  In my case I have a mixture of small and large files in the bucket and spreading out the downloading of them across a cluster, so the extra GET is multiplied by number of nodes.  The larger the file, the less of an issue it is.

Ive been looking through the code and the interfaces available in golang thinking of how it can be achieved.   Do we want to make a separate item for tracking the reuse of the 1st GET?  Or we can repurpose this item for that.    Have you looked at the WriterAt type?  It looks like we could utilize that and the characteristic that it allows parallel writes as long as the ranges do not overlap, which with multipart downloads, we also have the characteristic that ranges do not overlap.  

I am going to be looking at it some more this week and would have no problem helping out with it.   I also think I could utilize the WriterAt at the higher level to parallelize multiple downloads which are being concat into a file (taking those small files and getting them into a larger one before ingestion)

**Comment by rlmcpherson** [comment]
This tool has been optimized for streaming large files so that's been the focus. I'm open to a pull request that reuses the first get as long as it doesn't add a huge amount of complexity to the getter internal logic. If you want to open another issue or continue the discussion here, either way is fine with me.

As far as the WriterAt type and concatenating files, I'm not sure I understand what you are trying to do.

**Comment by rlmcpherson** [comment]
Closing this issue as HEAD does not return error information as discussed above.
