### ISSUE TITLE
any chance of a windows binary release ?

### ISSUE THREAD

**Issue by joeblew99** [rlmcpherson/s3gof3r#86]
so of the dudes on the dev team use windows, and we use S3 and your tool this for anything we cant put in git.

thanks in advance...

**Comment by rlmcpherson** [comment]
I haven't released a windows version since I've never tested on windows, but I'll add a windows release to the latest version since there's interest. For continued windows support, I'll need help with reporting and testing any windows issues since I don't use that platform and don't have time to test. Can you help with that?

**Comment by joeblew99** [comment]
Yep there are some guys here in the team on windows, so you will definitely get issues

**Comment by joeblew99** [comment]
Thanks

**Comment by rlmcpherson** [comment]
Thanks! I added a windows binary to the 0.5.0 release.

**Comment by joeblew99** [comment]
Thankyou !!
