### ISSUE TITLE
path problem ?

### ISSUE THREAD

**Issue by joeblew99** [rlmcpherson/s3gof3r#87]
Env: osx
golang 1.5.2

AWS credentials on env.

But am getting:
```
gof3r_0.5.0_amd64_darwin get -b appdif.dev -k test/f2/log2.txt | tar -x: No such file or directory

```

the file is on this s3 path:
https://console.aws.amazon.com/s3/home?region=eu-central-1&bucket=appdif.dev&prefix=test/f2/

Any ideas ?

**Comment by rlmcpherson** [comment]
I was able to download the file but it is only 15 bytes and tar does not recognize the format of the file. It may be corrupted. One thing to remember when uncompressing a tar stream is that the compression format needs to be specified explicitly as in `tar -xzf` rather than `tar -xf` since tar can not determine the compression type from the first few bytes of the stream. 

This doesn't look like a gof3r issue so I'm closing it for now. Please reopen if there's still an issue.
